In [4]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [5]:
data = pd.read_csv("Population_Survey_Data_lyst1750274390196.csv")
data.head()

   ID  Age Gender  Income  Education Region
0   1   62  Other   96138    Masters   East
1   2   65  Other   76543        PhD   East
2   3   71   Male  138887  Bachelors   East
3   4   18  Other  121643  Bachelors  South
4   5   21   Male  143192    Masters   East

In [6]:
data.shape

(1000, 6)

1.Simple Randome Sampling: Fetch 100 records ramdomly

In [8]:
sample_data = data.sample(n=100, random_state=44)
sample_data

      ID  Age  Gender  Income    Education Region
118  119   31    Male   71544      Masters   West
19    20   19  Female   67628    Bachelors  North
41    42   42    Male  107471  High School   West
425  426   64    Male   55738          PhD  South
221  222   31    Male   78882    Bachelors   East
..   ...  ...     ...     ...          ...    ...
143  144   39    Male   69453  High School   West
840  841   72   Other  103702    Bachelors   West
763  764   68  Female  106461      Masters  South
526  527   24  Female   24440    Bachelors   East
316  317   44  Female  132092    Bachelors   East

[100 rows x 6 columns]

2. Stratified Sampling:

In [10]:
stratified_sample_data = data.groupby('Region').apply(lambda x: x.sample(min(len(x), 25), random_state=44))
stratified_sample_data

             ID  Age  Gender  Income    Education
Region
East   845  846   23   Other  120266  High School
       215  216   22   Other   74772      Masters
       613  614   42    Male   51523      Masters
       974  975   26   Other   24789          PhD
       774  775   26    Male   53525          PhD
...         ...  ...     ...     ...          ...
West   896  897   78  Female   21549    Bachelors
       374  375   30  Female   59892          PhD
       511  512   24   Other   65074          PhD
       520  521   40    Male   62139  High School
       39    40   36    Male   85031  High School

[100 rows x 5 columns]

3.Cluster Sampling: Manufacturing data by batch number

In [12]:
manufacturing_data = pd.read_csv("Manufacturing_Data_lyst1750274395200.csv")
manufacturing_data.head()

   ProductID  BatchNumber ProductionDate  Defective      Weight     Length
0          1           25     2024-01-09          0  462.453744  17.613212
1          2           45     2024-04-18          0  521.766704  15.899234
2          3           20     2024-04-11          0  498.369030  14.177899
3          4           31     2024-06-27          0  488.938762  16.498599
4          5           14     2023-10-27          0  524.459295  15.422276

In [13]:
clusters = manufacturing_data['BatchNumber'].unique()
clusters

array([25, 45, 20, 31, 14,  8, 36, 30, 21,  9, 11, 42, 35, 47, 12, 22,  5,
       48, 23,  7, 44, 33, 38,  4, 18,  6, 28,  2, 34, 41, 40, 19, 16, 46,
       49, 43, 17,  3, 13, 10, 29, 32, 24, 26, 39, 15,  1, 27, 37])

In [14]:
selected_clusters = np.random.choice(clusters, size=5, replace=False)
selected_clusters

array([39, 11, 19, 20, 22])

In [15]:
clustered_sample = manufacturing_data[manufacturing_data['BatchNumber'].isin(selected_clusters)]
clustered_sample

     ProductID  BatchNumber ProductionDate  Defective      Weight     Length
2            3           20     2024-04-11          0  498.369030  14.177899
6            7           20     2023-12-19          0  511.999735  13.969603
11          12           11     2024-04-27          0  488.304581  16.396339
17          18           22     2024-05-25          0  473.413269  18.979386
21          22           22     2023-12-22          0  526.228543  13.594331
..         ...          ...            ...        ...         ...        ...
947        948           20     2023-10-18          0  531.014412  13.289830
950        951           11     2024-04-26          1  507.839382  14.437701
951        952           19     2024-04-24          0  511.285743  17.358671
981        982           20     2023-12-07          0  493.793915  16.102068
992        993           39     2024-01-06          0  482.527387  14.910282

[88 rows x 6 columns]

4.Systematic Sampling

In [16]:
systematic_sample = data.iloc[::10, :]
systematic_sample

      ID  Age  Gender  Income    Education Region
0      1   62   Other   96138      Masters   East
10    11   39    Male   25241      Masters   West
20    21   56   Other  121272          PhD  South
30    31   27  Female   58115  High School   East
40    41   53  Female  147482    Bachelors  North
..   ...  ...     ...     ...          ...    ...
950  951   78    Male  121159          PhD  North
960  961   55  Female   34823    Bachelors  South
970  971   36   Other  108570    Bachelors  South
980  981   77  Female  123554    Bachelors  North
990  991   28  Female  139725      Masters  North

[100 rows x 6 columns]

Evaluate the measures of central tendency for the whole data followed by the simple random sample, stratified sample, cluster sample and systematic sample.
Compare the means of all the different types of sample.
Finally, conclude which specific technique mean value is almost similar to the population mean value.

In [27]:
population_mean = data['Income'].mean()
print("Population")
print(f"Mean: {population_mean}")
population_median = data['Income'].median()
print(f"Median: {population_median}")
population_mode = data['Income'].mode()[0]
print(f"Mode: {population_mode}")

Population
Mean: 85147.959
Median: 85589.5
Mode: 52869

In [28]:
sample_size = int(len(data)*0.20)

In [44]:
population_simple_random_sample = data.sample(n=sample_size, random_state=42)
print("Simple Random Sampling")
random_mean = population_simple_random_sample['Income'].mean()
print(f"Mean: {random_mean}")
random_median = population_simple_random_sample['Income'].median()
print(f"Median: {random_median}")
random_mode = population_simple_random_sample['Income'].mode()[0]
print(f"Mode: {random_mode}")

Simple Random Sampling
Mean: 87185.23
Median: 88538.0
Mode: 52869

In [58]:
population_stratified_sample = data.groupby("Education").apply(lambda x: x.sample(min(len(x),20), random_state=42))

print("Stratified Sampling")
stratified_mean = population_stratified_sample['Income'].mean()
print(f"Mean: {stratified_mean}")
stratified_median = population_stratified_sample['Income'].median()
print(f"Median: {stratified_median}")
stratified_mode = population_stratified_sample['Income'].mode()[0]
print(f"Mode: {stratified_mode}")

Stratified Sampling
Mean: 80905.6875
Median: 77907.0
Mode: 20851

In [63]:
population_clusters = data['Education'].unique()


population_selected_clusters = np.random.choice(population_clusters, size=3, replace=False)


population_clustered_sample = data[data['Education'].isin(population_selected_clusters)]


print("Cluster Sampling")
clustered_mean = population_clustered_sample['Income'].mean()
print(f"Mean: {clustered_mean}")
clustered_median = population_clustered_sample['Income'].median()
print(f"Median: {clustered_median}")
clustered_mode = population_clustered_sample['Income'].mode()[0]
print(f"Mode: {clustered_mode}")

Cluster Sampling
Mean: 83852.66847090663
Median: 83076.0
Mode: 52869

In [65]:
population_systematic_sample = data.iloc[::10, :]

print("Systematic Sampling")
systematic_mean = population_systematic_sample['Income'].mean()
print(f"Mean: {systematic_mean}")
systematic_median = population_systematic_sample['Income'].median()
print(f"Median: {systematic_median}")
systematic_mode = population_systematic_sample['Income'].mode()[0]
print(f"Mode: {systematic_mode}")

Systematic Sampling
Mean: 88961.4
Median: 94080.0
Mode: 23962

In [69]:
results = {
    "Population":{
        "Mean": population_mean,
        "Median": population_median,
        "Mode": population_mode
    },
    "Random Sampling":{
        "Mean": random_mean,
        "Median": random_median,
        "Mode": random_mode
    },
    "Stratified Sampling": {
        "Mean": stratified_mean,
        "Median": stratified_median,
        "Mode": stratified_mode
    },
    "Cluster Sampling":{
        "Mean": clustered_mean,
        "Median": clustered_median,
        "Mode": clustered_mode
    },
    "Systematic Sampling":{
        "Mean": systematic_mean,
        "Median": systematic_median,
        "Mode": systematic_mode
    }
}

pd.DataFrame(results).T

                             Mean   Median     Mode
Population           85147.959000  85589.5  52869.0
Random Sampling      87185.230000  88538.0  52869.0
Stratified Sampling  80905.687500  77907.0  20851.0
Cluster Sampling     83852.668471  83076.0  52869.0
Systematic Sampling  88961.400000  94080.0  23962.0